server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 86400

spring:
  application:
    name: sun-picture-backend
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
  session:
    timeout: 86400
    store-type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.76.101:3306/sun-picture
    username: sun-picture
    password: 1798

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.suny.picture.controller
# knife4j的增强配置，不需要增强可以不配
# 接口文档配置
knife4j:
  enable: true
  openapi:
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.suny.picture.controller
    title: sun-picture-backend
